<?php

function vigotech_block_info() {
  $blocks = [];

  $blocks['claim'] = [
    'info' => t('VigoTech Alliance'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  ];
  return $blocks;
}


function vigotech_block_view($delta = '') {

  switch ($delta) {
    case 'claim':
      if (user_access('access content')) {
        $block = [
          'subject' => '',
          'content' => [
            '#markup' => l(
              t('Proudly made with !icon in <strong>Vigo</strong>', ['!icon' => '<i class="vt-pinecone"></i>']),
              'https://vigotech.org',
              [
                'attributes' => [
                  'class' => 'vigotech-claim',
                ],
                'html' => TRUE
              ]
            ),
            '#attached' => array(
              'css' => array(
                drupal_get_path('module', 'vigotech') . '/assets/css/madeinvigotech.css',
              ),
            ),
          ]
        ];

        echo drupal_get_path('module', 'vigotech');

        return $block;
      }
      break;
  }
}
